#!/bin/bash
#
#   Install spack into the current system
#
#   Author:         Brian Vanderwende
#   Last Revised:   20:32, 18 Feb 2022
#

set -e
export NCAR_SPACK_INSTALL_TIME=$(date +%y%m%d%H%M)
export NCAR_SPACK_INSTALL_DIR="$( cd "$(dirname "$0")" ; pwd )"

#
## ---- INITIALIZATION ----
#

# Make sure environment is clean
if [[ -n $MODULEPATH_ROOT ]]; then
    $NCAR_SPACK_INSTALL_DIR/bin/clean_bash $0 $@
    exit $?
fi

# Source global settings
. $NCAR_SPACK_INSTALL_DIR/etc/global.cfg

# HACK! -   Python3 is too old on Cheyenne and not installed at all
#           on Casper, so we add a compiled Python3 here. For future
#           deployments, make sure HSG has sufficient Python3 installed
if [[ $(hostname) == cheyenne* ]]; then
    export PATH=/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/bin:$PATH
else
    export PATH=/glade/u/apps/dav/opt/python/3.7.9/gnu/9.1.0/bin:$PATH
fi

#
## ---- INSTALL SPACK ----
#

if [[ -d $NCAR_ROOT_SPACK ]]; then
cat << EOF
Error:  Spack install already exists at ${NCAR_ROOT_SPACK}!
        Please manually clean up if reinstall is desired...
        
EOF
exit 1
fi

# Install latest source from GitHub and checkout specified version
echo "Installing Spack into $NCAR_ROOT_SPACK ..."
git clone -c feature.manyFiles=true https://github.com/spack/spack.git $NCAR_ROOT_SPACK
cd $NCAR_ROOT_SPACK
git checkout $NCAR_SPACK_VERSION

# Copy clean shell scripts to Spack bin
cp $NCAR_SPACK_INSTALL_DIR/bin/clean* $NCAR_ROOT_SPACK/bin/

echo "Restricting maximum build jobs to $MAX_BUILD_JOBS ..."
echo "Setting cache paths to /glade/scratch/\$user/temp ..."
cat > $NCAR_ROOT_SPACK/etc/spack/config.yaml << EOF
config:
  build_jobs: $MAX_BUILD_JOBS
  test_stage: /glade/scratch/\$user/temp/spack-test
  source_cache: /glade/scratch/\$user/temp/spack-cache
  build_stage:
    - /glade/scratch/\$user/temp/spack-stage
EOF

# Modify permissions according
chgrp -R csgteam $NCAR_ROOT_SPACK
chmod -R a=rX,u+w $NCAR_ROOT_SPACK

# Activate spack installation
. $NCAR_ROOT_SPACK/share/spack/setup-env.sh

# Create trusted GPG key in spack install
echo "Creating trusted GPG key for build cache creation ..."
spack gpg create "NCAR CSG Spack" "<csg@ucar.edu>"

# Allow group access to keys
chmod -R g+rwX $NCAR_ROOT_SPACK/opt/spack/gpg

echo -e "Install complete\n"
