#!/bin/bash
#
#   This script prepares the common env for public use
#

# Perform common script setup including environment checks
export my_dir="$( cd "$(dirname "$0")" ; pwd )"
. $my_dir/tools/init.sh

# Only run this for the public env
if [[ $SPACK_ENV != $NCAR_SPACK_ENV_PUBLIC ]]; then
   exit
fi

log_active=0

while [[ $# -gt 0 ]]; do
    case $1 in
        -v|--verbose)
            echo
            log_active=1
            ;;
    esac

    shift
done


for nv_version in $(spack find --format "{version}" nvhpc | grep -v "==>"); do
    [[ $log_active == 1 ]] && echo -e "Checking nvhpc/${nv_version} for CUDA bloat ..."
    nv_root=$(spack location -i nvhpc@$nv_version)
    cuda_root=$nv_root/Linux_x86_64/$nv_version/cuda
    math_root=$nv_root/Linux_x86_64/$nv_version/math_libs
    cuda_default=$(readlink -f $cuda_root/bin | sed 's|.*/\(.*\)/bin|\1|')
    [[ $log_active == 1 ]] && echo "  - default CUDA version is v$cuda_default"

    for comp_root in $cuda_root $math_root; do
        for this_cuda_dir in $(find $comp_root -mindepth 1 -maxdepth 1 -type d); do
            this_cuda=$(basename $this_cuda_dir)

            if [[ $this_cuda != $cuda_default ]]; then
                [[ $log_active == 1 ]] && echo "  - removing unnecessary CUDA v$this_cuda components ..."
                rm -rf $this_cuda_dir
            fi
        done
    done
done

# Need to fix a symbolic link in the public OpenSSL environment because of Spack issue
# https://github.com/spack/spack/issues/31401
[[ $log_active == 1 ]] && echo -e "Checking OpenSSL cert link (Spack issue 31401) ..."
cert_file=$(spack location -i ca-certificates-mozilla)/share/cacert.pem
cert_link=$(spack location -i openssl)/etc/openssl/cert.pem

if [[ $(readlink -f $cert_link) != $cert_file ]]; then
    [[ $log_active == 1 ]] && echo "  - replacing cert link with public path ..."
    ln -sf $cert_file $cert_link
fi

# Need to create a symbolic link for libxml in the view
cd $NCAR_SPACK_ROOT_VIEW/include

if [[ ! -e libxml ]]; then
    [[ $log_active == 1 ]] && echo -e "Creating symlink in view for libxml ..."
    ln -sf libxml2/libxml libxml
fi
