#!/bin/bash
#
#   This script prepares the common env for public use
#

# Only run this for the public env
if [[ $SPACK_ENV != $NCAR_SPACK_ENV_PUBLIC ]]; then
   exit
fi

# Perform common script setup including environment checks
export my_dir="$( cd "$(dirname "$0")" ; pwd )"
. $my_dir/tools/init.sh

log_active=0

while [[ $# -gt 0 ]]; do
    case $1 in
        -v|--verbose)
            log_active=1
            ;;
    esac

    shift
done

for nv_version in $(spack find --format "{version}" nvhpc); do
    [[ $log_active == 1 ]] && echo -e "\nChecking nvhpc/${nv_version} for CUDA bloat ..."
    nv_root=$(spack location -i nvhpc@$nv_version)
    cuda_root=$nv_root/Linux_x86_64/$nv_version/cuda
    cuda_default=$(readlink -f $cuda_root/bin | sed 's|.*/\(.*\)/bin|\1|')
    [[ $log_active == 1 ]] && echo "  - default CUDA version is v$cuda_default"

    for this_cuda_dir in $(find $cuda_root -mindepth 1 -maxdepth 1 -type d); do
        this_cuda=$(basename $this_cuda_dir)

        if [[ $this_cuda != $cuda_default ]]; then
            [[ $log_active == 1 ]] && echo "  - removing unnecessary CUDA v$this_cuda ..."
            rm -rf $this_cuda_dir
        fi
    done    
done
